// src/app/components/account/account.component.ts
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';
import {Account} from "../../model/account";
import {Operation} from "../../model/operation";
import { OperationService } from "../../services/operationService/operation.service";

@Component({
  selector: 'app-account',
  templateUrl: './account.component.html',
  styleUrls: ['./account.component.css']
})
export class AccountComponent implements OnInit {
  @Output() accountsRowClick: EventEmitter<any> = new EventEmitter();
  @Input() account: any;
  isDetailsSelected: boolean = false;
  operations: Operation[] = new Array<Operation>();

  constructor(public operationService: OperationService ) { }

  ngOnInit() {
    var component = this;
    component.account.operationsList.forEach(function (operation) {
      component.operationService.getOperations(operation).subscribe(data => {
        console.log(data);
        component.operations.push(data);
      });
    })
  }

  detailsSelected () {
    this.isDetailsSelected = !this.isDetailsSelected;
  }

  accountRowClick(id: string) {
    this.accountsRowClick.emit(id);
  }

}

<div class="c-list-item">
  <div class="c-list-item__title" (click)="accountRowClick(account.id);">
    <div>Compte courant
      <div class="c-field c-field--left c-list-item__subtitle">
        <div class="c-field__label">N° de compte:</div>
        <div class="c-field__value">{{account.accountNumber}}</div>
      </div>
    </div>
    <div class="c-list-item__actions fa fa-angle-right"></div>
  </div>
  <div class="c-list-item__content js-account-details" [class.is-selected]="isDetailsSelected" (click)="detailsSelected()">
    <div class="c-field">
      <div class="c-field__label"></div>
      <div class="c-field__value">{{account.balance}} {{account.currency}} <span class="down fa fa-angle-down"></span></div>
    </div>
    <div class="c-list-item__detail" *ngFor="let operation of operations">
      <app-operation [operation]="operation"></app-operation>

    </div>
  </div>
</div>

// src/app/components/Account.vue
<template>
    <div>
        <a class="c-list-item__title" v-on:click="clickOnRow(account.id)">
            <div>
                Compte courant
                <div class="c-field c-field--left c-list-item__subtitle">
                    <div class="c-field__label">N° de compte:</div>
                    <div class="c-field__value"><span >{{ account.accountNumber }}</span></div>
                </div>
            </div>
            <div class="c-list-item__actions fa fa-angle-right"></div>
        </a>
        <div class="c-list-item__content js-account-details" v-bind:class="{'is-selected': isDetailsOpen}" v-on:click="clickOnDetails">
            <div class="c-field">
                <div class="c-field__label"></div>
                <div class="c-field__value">{{ account.balance }} euros<span class="down fa fa-angle-down"></span></div>
            </div>
            <div class="c-list-item__detail" v-for="operation in operations">
                <accountOperation :operation=operation></accountOperation>
            </div>
        </div>
    </div>
</template>

<script>
    import AccountOperation from './AccountOperation.vue';
    import axios from 'axios';
    export default {
        name: 'account',
        props: ['account', 'clickOnRow'],
        components: {
            AccountOperation
        },
        data() {
            const data = {
                operations: [],
                isDetailsOpen: false
            }
            return data;
        },
        mounted:function(){
            this.fetchData();
        },
        methods: {
            fetchData: function(){


                var vm = this;
                // On appelle la liste des opérations du compte
                this.account.operationsList.forEach(function (operation) {
                    console.log('operation', operation);
                    vm.fetchOperation('operations/'+operation)
                            .then(function(response) {
                                vm.operations.push(response.data);
                            });
                })

            },
            fetchOperation: function(url) {
                return axios.get(url);
            },
            clickOnDetails: function () {
                console.log('test', this.isDetailsOpen );
                this.isDetailsOpen = !this.isDetailsOpen;
            }
        }
    };
</script>
