// src/app/components/bandeau/bandeau.component.ts
import { Component, OnInit } from '@angular/core';
import { ClientService } from '../../services/clientService/client.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-bandeau',
  templateUrl: './bandeau.component.html',
  styleUrls: ['./bandeau.component.css']
})
export class BandeauComponent implements OnInit {
  isOpened: boolean = false;
  constructor(private clientService: ClientService, public routeur: Router) { }

  ngOnInit() {
  }

  menuOpen(event: Event) {
    this.isOpened = !this.isOpened;
  }

  logout(event: Event) {
    var component = this;
    this.clientService.logout()
      .then(
        function () {
          component.routeur.navigate(['/login']);
        })
      .catch(
        error => {
          console.log(error);
        });
  }

}

<div class="o-panel-header">
  <h1 class="c-logo">
    <svg height="2em" viewBox="0 0 20 20" preserveAspectRatio="xMinYMid">
      <use xlink:href="#logo-min"></use>
    </svg>
  </h1>
  <div class="c-user menu-container js-user-menu" [class.is-opened]="isOpened" (click)="menuOpen()" >
    <div class="fa fa-user-circle-o c-user__ico"></div>
    Hervé Lepinard
    <div class="fa fa-angle-down"></div>
    <ul class="menu">
      <li class="menu__item"><a routerLink="/app/accounts"><span class="fa fa-gear"></span> Mes comptes</a></li>
      <li class="menu__item"><a routerLink="/app/virement/debiter"><span class="fa fa-gear"></span> Faire un virement</a></li>
      <li class="menu__item" (click)="logout()"><a href="#"><span class="fa fa-unlock-alt"></span> Logout</a></li>
    </ul>
  </div>
  <div class="c-options"></div>
</div>

// src/app/components/Bandeau.vue
<template>
    <div class="o-panel-header">
        <h1 class="c-logo">
            <svg height="2em" viewBox="0 0 20 20" preserveAspectRatio="xMinYMid">
            <use xlink:href="#logo-min"></use>
            </svg>
        </h1>
        <div class="c-user menu-container js-user-menu">
            <div class="fa fa-user-circle-o c-user__ico"></div>
            Hervé Lepinard
            <div class="fa fa-angle-down"></div>
            <ul class="menu">
                <li class="menu__item"><a href="#"><span class="fa fa-gear"></span> Preferences</a>
                <li class="menu__item"><a href="/login.html"><span class="fa fa-unlock-alt"></span> Logout</a>
            </ul>
        </div>
        <div class="c-options"></div>
    </div>
</template>

<script>
export default{
    name: 'bandeau'
}
</script>
