// src/app/components/Cartographie.vue
<template>
    <div>
        <div class="floating-btn-group floating-btn-group--inverted">
            <div class="btn fa fa-globe js-localization"></div>
        </div>
        <div class="overlay js-localization-modal" aria-hidden="true">
            <div class="modal">
                <div class="btn btn-close js-close"><div class="fa fa-close"></div></div>
                <div style="width:50vw;max-width:100%;overflow:hidden;height:60vh;">
                    <div id="gmap-canvas">
                        <iframe
                                style="height:100%;width:100%;border:0;"
                                frameborder="0"
                                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBSXVSIegDwxmT3vc1AuiEUDRmunfjDP1w&q=Brooklyn+Bridge,New-York+NY&zoom=16">
                        </iframe>
                    </div><!-- AIzaSyCMZCsMSV5KhnOaKVGfxidaR60q6ZH6O9M-->
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default{
        name: 'cartographie'
    }
</script>

<style>
    #gmap-canvas img{
        max-width:none!important;
        background:none!important;
    }
</style>

// src/app/cartographie/cartographie.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cartographie',
  templateUrl: './cartographie.component.html',
  styleUrls: ['./cartographie.component.css']
})
export class CartographieComponent implements OnInit {
  isAriaHidden: boolean = true;

  constructor() { }

  ngOnInit() {
  }

  clickOpenModal(event) {
    this.isAriaHidden = false;
    console.log('clickOpenModal', this.isAriaHidden);
  }

  clickCloseModal(event) {
    this.isAriaHidden = true;
    console.log('clickOpenModal', this.isAriaHidden);
  }

}

<div class="floating-btn-group floating-btn-group--inverted" (click)="clickOpenModal()">
  <div class="btn fa fa-globe js-localization"></div>
</div>
<div class="overlay js-localization-modal" [attr.aria-hidden]="isAriaHidden">
  <div class="modal">
    <div class="btn btn-close js-close" (click)="clickCloseModal()"><div class="fa fa-close"></div></div>
    <div style="width:50vw;max-width:100%;overflow:hidden;height:60vh;">
      <div id="gmap-canvas">
        <iframe
          style="height:100%;width:100%;border:0;"
          frameborder="0"
          src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBSXVSIegDwxmT3vc1AuiEUDRmunfjDP1w&q=Brooklyn+Bridge,New-York+NY&zoom=16">
        </iframe>
      </div><!-- AIzaSyCMZCsMSV5KhnOaKVGfxidaR60q6ZH6O9M-->
      <style>#gmap-canvas img{max-width:none!important;background:none!important;}</style>
    </div>
  </div>
</div>

<!-- GOOGLE MAPS -->
<script>
  function initMap() { var uluru = {lat: -25.363, lng: 131.044}; var map = new google.maps.Map(document.getElementById('map'), { zoom: 4, center: uluru }); var marker = new google.maps.Marker({ position: uluru, map: map }); }
</script>
<script defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSXVSIegDwxmT3vc1AuiEUDRmunfjDP1w&callback=initMap"> </script>
